<a href="https://colab.research.google.com/github/Raquelsantosb/analise-dados-python/blob/main/Implementa%C3%A7%C3%A3odaPCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'Class']
datasets = pd.read_csv(url, names=names)
import plotly.express as px

In [ ]:
from sklearn.model_selection import train_test_split
X = datasets.drop(columns='Class')
y = datasets['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

for i in range(X_train.shape[1]):
  pca = PCA(n_components=i+1)
  pca_X_train = pca.fit_transform(X_train)
  pca_X_test = pca.transform(X_test)

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(pca_X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(pca_X_test)
cm = confusion_matrix(y_test, y_pred)
print ("---------------------------------------------------------------")
print("PCA: ", i+1)
print(cm)
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Dataset Var: ', pca_X_train.var())
for c in range(pca_X_train.shape[1]):
    print("Component(",c+1,"):", pca_X_train[c].var())
print("---------------------------------------------------------------")


---------------------------------------------------------------
PCA:  3
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Accuracy: 1.0
Dataset Var:  1.0000000000000002
Component( 1 ): 0.13210030656110774
Component( 2 ): 0.04959137936273696
Component( 3 ): 1.139424659322578
---------------------------------------------------------------
